version: "3"
services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    working_dir: /app
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:5.7.39
    volumes:
      - /mysql-data/:/var/lib/mysql
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "-u$DATABASE_USER",
          "-p$DATABASE_PASSWORD",
          "ping",
          "-h",
          "database",
        ]
      timeout: 20s
      retries: 10

  cache:
    image: redis:7.0.4