version: "3"
services:
  app:
    image: node:18.9.0-alpine3.16
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    restart: always
    working_dir: /app
    command: sh -c "yarn prisma generate && yarn prisma db push && yarn dev"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}
    depends_on:
      database:
         condition: service_healthy

  database:
    image: mariadb:10.9.2
    environment:
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$DATABASE_USER", "-p$DATABASE_PASSWORD",  "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
